### ISSUE TITLE
How to use the clear_emoticon() method?

### ISSUE THREAD

**Issue by ghost** [ifrost/droopy#1]
hi, been trying our your module to do some text processing. After doing a "from droopy.filters import TextFilter" I am not sure how to use it. When I do a `TextFilter.<tab><tab>` I get only .clear_text and .mro methods listed and not functions defined here https://github.com/ifrost/droopy/blob/master/droopy/filters.py.

I am using ipython. Thanks!

**Comment by ifrost** [comment]
You have to create a droopy object:

```
from droopy import Droopy
from droopy.lang.english import English

droopy = DroopyFactory.create_full_droopy("Hello :) How are you?", English())

droopy.without_emoticons
> u'Hello . How are you?'
```

or using operator:

```
droopy.clear_emoticons("Wow :P")
> u'Wow .'
```

... but to be honest filtering emoticons is very limited. You can create own bundle (see https://github.com/ifrost/droopy/blob/master/examples/custom_bundle.py) that filters out more emoticons.

**Comment by ghost** [comment]
It just occurred to me, why haven't you used a regular expression to filter out emoticons?
Thank you for the answer, its clear to me now. :+1:
